class PredefinedItemExtraSeed {
  const PredefinedItemExtraSeed(this.categoryIndex, this.names);

  final int categoryIndex;
  final Map<String, String> names;
}

const List<PredefinedItemExtraSeed> predefinedItemExtraSeeds = [
  PredefinedItemExtraSeed(0, {
    'pl': 'Woda smakowa',
    'en': 'Flavored water',
    'de': 'Aromatisiertes Wasser',
    'nl': 'Water met smaak',
    'es': 'Agua con sabor',
    'fr': 'Eau aromatisée',
    'uk': 'Ароматизована вода',
    'it': 'Acqua aromatizzata',
    'pt': 'Água aromatizada',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Oranżada',
    'en': 'Orangeade',
    'de': 'Orangenlimonade',
    'nl': 'Sinaasappellimonade',
    'es': 'Naranjada',
    'fr': 'Orangeade',
    'uk': 'Помаранчевий лимонад',
    'it': 'Aranciata',
    'pt': 'Laranjada',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Tonik',
    'en': 'Tonic water',
    'de': 'Tonic Water',
    'nl': 'Tonic',
    'es': 'Tónica',
    'fr': 'Eau tonique',
    'uk': 'Тонік',
    'it': 'Acqua tonica',
    'pt': 'Água tónica',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Napój cytrynowy',
    'en': 'Lemon drink',
    'de': 'Zitronengetränk',
    'nl': 'Citroendrank',
    'es': 'Bebida de limón',
    'fr': 'Boisson au citron',
    'uk': 'Лимонний напій',
    'it': 'Bevanda al limone',
    'pt': 'Bebida de limão',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Napój pomarańczowy',
    'en': 'Orange drink',
    'de': 'Orangengetränk',
    'nl': 'Sinaasappeldrank',
    'es': 'Bebida de naranja',
    'fr': 'Boisson à l’orange',
    'uk': 'Апельсиновий напій',
    'it': 'Bevanda all’arancia',
    'pt': 'Bebida de laranja',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Napój energetyczny',
    'en': 'Energy drink',
    'de': 'Energy-Drink',
    'nl': 'Energiedrank',
    'es': 'Bebida energética',
    'fr': 'Boisson énergisante',
    'uk': 'Енергетичний напій',
    'it': 'Bevanda energetica',
    'pt': 'Bebida energética',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Napój izotoniczny',
    'en': 'Isotonic drink',
    'de': 'Isotonisches Getränk',
    'nl': 'Isotone drank',
    'es': 'Bebida isotónica',
    'fr': 'Boisson isotonique',
    'uk': 'Ізотонічний напій',
    'it': 'Bevanda isotonica',
    'pt': 'Bebida isotónica',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Ice tea',
    'en': 'Iced tea',
    'de': 'Eistee',
    'nl': 'IJsthee',
    'es': 'Té helado',
    'fr': 'Thé glacé',
    'uk': 'Холодний чай',
    'it': 'Tè freddo',
    'pt': 'Chá gelado',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Sok multiwitamina',
    'en': 'Multivitamin juice',
    'de': 'Multivitaminsaft',
    'nl': 'Multivitaminesap',
    'es': 'Zumo multivitamínico',
    'fr': 'Jus multivitaminé',
    'uk': 'Мультивітамінний сік',
    'it': 'Succo multivitaminico',
    'pt': 'Sumo multivitamínico',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Sok grejpfrutowy',
    'en': 'Grapefruit juice',
    'de': 'Grapefruitsaft',
    'nl': 'Grapefruitsap',
    'es': 'Zumo de pomelo',
    'fr': 'Jus de pamplemousse',
    'uk': 'Грейпфрутовий сік',
    'it': 'Succo di pompelmo',
    'pt': 'Sumo de toranja',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Sok pomidorowy',
    'en': 'Tomato juice',
    'de': 'Tomatensaft',
    'nl': 'Tomatensap',
    'es': 'Zumo de tomate',
    'fr': 'Jus de tomate',
    'uk': 'Томатний сік',
    'it': 'Succo di pomodoro',
    'pt': 'Sumo de tomate',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Sok z czarnej porzeczki',
    'en': 'Blackcurrant juice',
    'de': 'Schwarzer Johannisbeersaft',
    'nl': 'Zwartebessensap',
    'es': 'Zumo de grosella negra',
    'fr': 'Jus de cassis',
    'uk': 'Сік чорної смородини',
    'it': 'Succo di ribes nero',
    'pt': 'Sumo de groselha preta',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Kompot',
    'en': 'Compote drink',
    'de': 'Kompott',
    'nl': 'Compote',
    'es': 'Compota',
    'fr': 'Compote',
    'uk': 'Компот',
    'it': 'Composta',
    'pt': 'Compota',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Kawa ziarnista',
    'en': 'Coffee beans',
    'de': 'Kaffeebohnen',
    'nl': 'Koffiebonen',
    'es': 'Café en grano',
    'fr': 'Café en grains',
    'uk': 'Кава в зернах',
    'it': 'Caffè in grani',
    'pt': 'Café em grão',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Kawa bezkofeinowa',
    'en': 'Decaf coffee',
    'de': 'Entkoffeinierter Kaffee',
    'nl': 'Cafeïnevrije koffie',
    'es': 'Café descafeinado',
    'fr': 'Café décaféiné',
    'uk': 'Кава без кофеїну',
    'it': 'Caffè decaffeinato',
    'pt': 'Café descafeinado',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Herbata owocowa',
    'en': 'Fruit tea',
    'de': 'Früchtetee',
    'nl': 'Vruchtenthee',
    'es': 'Té de frutas',
    'fr': 'Thé aux fruits',
    'uk': 'Фруктовий чай',
    'it': 'Tè alla frutta',
    'pt': 'Chá de fruta',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Herbata ziołowa',
    'en': 'Herbal tea',
    'de': 'Kräutertee',
    'nl': 'Kruidenthee',
    'es': 'Té de hierbas',
    'fr': 'Tisane',
    'uk': 'Трав’яний чай',
    'it': 'Tisana',
    'pt': 'Chá de ervas',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Syrop owocowy',
    'en': 'Fruit syrup',
    'de': 'Fruchtsirup',
    'nl': 'Vruchtensiroop',
    'es': 'Sirope de frutas',
    'fr': 'Sirop de fruits',
    'uk': 'Фруктовий сироп',
    'it': 'Sciroppo alla frutta',
    'pt': 'Xarope de fruta',
  }),
  PredefinedItemExtraSeed(0, {
    'pl': 'Mleko roślinne',
    'en': 'Plant-based milk',
    'de': 'Pflanzliche Milch',
    'nl': 'Plantaardige melk',
    'es': 'Leche vegetal',
    'fr': 'Lait végétal',
    'uk': 'Рослинне молоко',
    'it': 'Latte vegetale',
    'pt': 'Leite vegetal',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Pierniki',
    'en': 'Gingerbread',
    'de': 'Lebkuchen',
    'nl': 'Peperkoek',
    'es': 'Pan de jengibre',
    'fr': 'Pain d’épices',
    'uk': 'Імбирне печиво',
    'it': 'Pan di zenzero',
    'pt': 'Pão de gengibre',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Biszkopty',
    'en': 'Sponge biscuits',
    'de': 'Löffelbiskuits',
    'nl': 'Lange vingers',
    'es': 'Bizcochos de soletilla',
    'fr': 'Biscuits à la cuillère',
    'uk': 'Бісквітне печиво',
    'it': 'Savoiardi',
    'pt': 'Palitos de champanhe',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Paluszki',
    'en': 'Pretzel sticks',
    'de': 'Salzstangen',
    'nl': 'Zoute sticks',
    'es': 'Palitos salados',
    'fr': 'Bâtonnets salés',
    'uk': 'Солоні палички',
    'it': 'Salatini',
    'pt': 'Palitos salgados',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Chipsy kukurydziane',
    'en': 'Corn chips',
    'de': 'Maischips',
    'nl': 'Maïschips',
    'es': 'Chips de maíz',
    'fr': 'Chips de maïs',
    'uk': 'Кукурудзяні чіпси',
    'it': 'Chips di mais',
    'pt': 'Chips de milho',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Landrynki',
    'en': 'Hard candy',
    'de': 'Bonbons',
    'nl': 'Harde snoepjes',
    'es': 'Caramelos duros',
    'fr': 'Bonbons durs',
    'uk': 'Льодяники',
    'it': 'Caramelle dure',
    'pt': 'Rebuçados',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Lizak',
    'en': 'Lollipop',
    'de': 'Lutscher',
    'nl': 'Lolly',
    'es': 'Piruleta',
    'fr': 'Sucette',
    'uk': 'Льодяник на паличці',
    'it': 'Lecca-lecca',
    'pt': 'Chupa-chupa',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Cukierki',
    'en': 'Candies',
    'de': 'Bonbons',
    'nl': 'Snoepjes',
    'es': 'Caramelos',
    'fr': 'Bonbons',
    'uk': 'Цукерки',
    'it': 'Caramelle',
    'pt': 'Doces',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Praliny',
    'en': 'Pralines',
    'de': 'Pralinen',
    'nl': 'Pralines',
    'es': 'Pralinés',
    'fr': 'Pralines',
    'uk': 'Пралінки',
    'it': 'Praline',
    'pt': 'Pralinés',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Guma do żucia',
    'en': 'Chewing gum',
    'de': 'Kaugummi',
    'nl': 'Kauwgom',
    'es': 'Chicle',
    'fr': 'Chewing-gum',
    'uk': 'Жувальна гумка',
    'it': 'Gomma da masticare',
    'pt': 'Pastilha elástica',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Chałwa',
    'en': 'Halva',
    'de': 'Halva',
    'nl': 'Halva',
    'es': 'Halva',
    'fr': 'Halva',
    'uk': 'Халва',
    'it': 'Halva',
    'pt': 'Halva',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Budyń',
    'en': 'Pudding',
    'de': 'Pudding',
    'nl': 'Pudding',
    'es': 'Pudin',
    'fr': 'Pudding',
    'uk': 'Пудинг',
    'it': 'Budino',
    'pt': 'Pudim',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Kisiel',
    'en': 'Kissel dessert',
    'de': 'Kissel',
    'nl': 'Kissel',
    'es': 'Kisel',
    'fr': 'Kissel',
    'uk': 'Кисіль',
    'it': 'Kissel',
    'pt': 'Kissel',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Galaretka',
    'en': 'Jelly dessert',
    'de': 'Wackelpudding',
    'nl': 'Gelei-dessert',
    'es': 'Gelatina',
    'fr': 'Gelée',
    'uk': 'Желе',
    'it': 'Gelatina',
    'pt': 'Gelatina',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Marshmallow',
    'en': 'Marshmallow',
    'de': 'Marshmallow',
    'nl': 'Marshmallow',
    'es': 'Malvavisco',
    'fr': 'Marshmallow',
    'uk': 'Маршмелоу',
    'it': 'Marshmallow',
    'pt': 'Marshmallow',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Sezamki',
    'en': 'Sesame snaps',
    'de': 'Sesamriegel',
    'nl': 'Sesamrepen',
    'es': 'Barritas de sésamo',
    'fr': 'Barres de sésame',
    'uk': 'Кунжутні козинаки',
    'it': 'Barrette di sesamo',
    'pt': 'Barras de sésamo',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Rogal słodki',
    'en': 'Sweet roll',
    'de': 'Süßes Hörnchen',
    'nl': 'Zoet broodje',
    'es': 'Bollo dulce',
    'fr': 'Petit pain sucré',
    'uk': 'Солодкий рогалик',
    'it': 'Cornetto dolce',
    'pt': 'Pão doce',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Ciasto czekoladowe',
    'en': 'Chocolate cake',
    'de': 'Schokoladenkuchen',
    'nl': 'Chocoladetaart',
    'es': 'Pastel de chocolate',
    'fr': 'Gâteau au chocolat',
    'uk': 'Шоколадний торт',
    'it': 'Torta al cioccolato',
    'pt': 'Bolo de chocolate',
  }),
  PredefinedItemExtraSeed(1, {
    'pl': 'Babka',
    'en': 'Babka cake',
    'de': 'Babka',
    'nl': 'Babka-cake',
    'es': 'Pastel babka',
    'fr': 'Gâteau babka',
    'uk': 'Бабка',
    'it': 'Torta babka',
    'pt': 'Bolo babka',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Limonka',
    'en': 'Lime',
    'de': 'Limette',
    'nl': 'Limoen',
    'es': 'Lima',
    'fr': 'Citron vert',
    'uk': 'Лайм',
    'it': 'Lime',
    'pt': 'Lima',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Morela',
    'en': 'Apricot',
    'de': 'Aprikose',
    'nl': 'Abrikoos',
    'es': 'Albaricoque',
    'fr': 'Abricot',
    'uk': 'Абрикос',
    'it': 'Albicocca',
    'pt': 'Alperce',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Nektarynka',
    'en': 'Nectarine',
    'de': 'Nektarine',
    'nl': 'Nectarine',
    'es': 'Nectarina',
    'fr': 'Nectarine',
    'uk': 'Нектарин',
    'it': 'Nettarina',
    'pt': 'Nectarina',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Malina',
    'en': 'Raspberry',
    'de': 'Himbeere',
    'nl': 'Framboos',
    'es': 'Frambuesa',
    'fr': 'Framboise',
    'uk': 'Малина',
    'it': 'Lampone',
    'pt': 'Framboesa',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Jeżyna',
    'en': 'Blackberry',
    'de': 'Brombeere',
    'nl': 'Braam',
    'es': 'Mora',
    'fr': 'Mûre',
    'uk': 'Ожина',
    'it': 'Mora',
    'pt': 'Amora',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Porzeczka',
    'en': 'Currant',
    'de': 'Johannisbeere',
    'nl': 'Aalbes',
    'es': 'Grosella',
    'fr': 'Groseille',
    'uk': 'Смородина',
    'it': 'Ribes',
    'pt': 'Groselha',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Wiśnia',
    'en': 'Sour cherry',
    'de': 'Sauerkirsche',
    'nl': 'Zure kers',
    'es': 'Guinda',
    'fr': 'Griotte',
    'uk': 'Вишня',
    'it': 'Amarena',
    'pt': 'Ginja',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Czereśnia',
    'en': 'Sweet cherry',
    'de': 'Süßkirsche',
    'nl': 'Zoete kers',
    'es': 'Cereza dulce',
    'fr': 'Cerise douce',
    'uk': 'Черешня',
    'it': 'Ciliegia dolce',
    'pt': 'Cereja doce',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Arbuz',
    'en': 'Watermelon',
    'de': 'Wassermelone',
    'nl': 'Watermeloen',
    'es': 'Sandía',
    'fr': 'Pastèque',
    'uk': 'Кавун',
    'it': 'Anguria',
    'pt': 'Melancia',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Melon',
    'en': 'Melon',
    'de': 'Melone',
    'nl': 'Meloen',
    'es': 'Melón',
    'fr': 'Melon',
    'uk': 'Диня',
    'it': 'Melone',
    'pt': 'Melão',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Granat',
    'en': 'Pomegranate',
    'de': 'Granatapfel',
    'nl': 'Granaatappel',
    'es': 'Granada',
    'fr': 'Grenade',
    'uk': 'Гранат',
    'it': 'Melagrana',
    'pt': 'Romã',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Awokado',
    'en': 'Avocado',
    'de': 'Avocado',
    'nl': 'Avocado',
    'es': 'Aguacate',
    'fr': 'Avocat',
    'uk': 'Авокадо',
    'it': 'Avocado',
    'pt': 'Abacate',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Kokos',
    'en': 'Coconut',
    'de': 'Kokosnuss',
    'nl': 'Kokosnoot',
    'es': 'Coco',
    'fr': 'Noix de coco',
    'uk': 'Кокос',
    'it': 'Cocco',
    'pt': 'Coco',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Daktyle',
    'en': 'Dates',
    'de': 'Datteln',
    'nl': 'Dadels',
    'es': 'Dátiles',
    'fr': 'Dattes',
    'uk': 'Фініки',
    'it': 'Datteri',
    'pt': 'Tâmaras',
  }),
  PredefinedItemExtraSeed(2, {
    'pl': 'Figi',
    'en': 'Figs',
    'de': 'Feigen',
    'nl': 'Vijgen',
    'es': 'Higos',
    'fr': 'Figues',
    'uk': 'Інжир',
    'it': 'Fichi',
    'pt': 'Figos',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Pietruszka',
    'en': 'Parsley root',
    'de': 'Petersilienwurzel',
    'nl': 'Wortelpeterselie',
    'es': 'Raíz de perejil',
    'fr': 'Racine de persil',
    'uk': 'Корінь петрушки',
    'it': 'Radice di prezzemolo',
    'pt': 'Raiz de salsa',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Seler',
    'en': 'Celery root',
    'de': 'Knollensellerie',
    'nl': 'Knolselderij',
    'es': 'Apionabo',
    'fr': 'Céleri-rave',
    'uk': 'Корінь селери',
    'it': 'Sedano rapa',
    'pt': 'Aipo-rábano',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Por',
    'en': 'Leek',
    'de': 'Lauch',
    'nl': 'Prei',
    'es': 'Puerro',
    'fr': 'Poireau',
    'uk': 'Порей',
    'it': 'Porro',
    'pt': 'Alho-francês',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Rukola',
    'en': 'Arugula',
    'de': 'Rucola',
    'nl': 'Rucola',
    'es': 'Rúcula',
    'fr': 'Roquette',
    'uk': 'Рукола',
    'it': 'Rucola',
    'pt': 'Rúcula',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Kapusta pekińska',
    'en': 'Chinese cabbage',
    'de': 'Chinakohl',
    'nl': 'Chinese kool',
    'es': 'Col china',
    'fr': 'Chou chinois',
    'uk': 'Пекінська капуста',
    'it': 'Cavolo cinese',
    'pt': 'Couve chinesa',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Bakłażan',
    'en': 'Eggplant',
    'de': 'Aubergine',
    'nl': 'Aubergine',
    'es': 'Berenjena',
    'fr': 'Aubergine',
    'uk': 'Баклажан',
    'it': 'Melanzana',
    'pt': 'Beringela',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Bataty',
    'en': 'Sweet potatoes',
    'de': 'Süßkartoffeln',
    'nl': 'Zoete aardappelen',
    'es': 'Batatas',
    'fr': 'Patates douces',
    'uk': 'Батати',
    'it': 'Patate dolci',
    'pt': 'Batatas-doces',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Rzodkiewka',
    'en': 'Radish',
    'de': 'Radieschen',
    'nl': 'Radijs',
    'es': 'Rábano',
    'fr': 'Radis',
    'uk': 'Редиска',
    'it': 'Ravanello',
    'pt': 'Rabanete',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Szczypiorek',
    'en': 'Chives',
    'de': 'Schnittlauch',
    'nl': 'Bieslook',
    'es': 'Cebollino',
    'fr': 'Ciboulette',
    'uk': 'Зелена цибуля',
    'it': 'Erba cipollina',
    'pt': 'Cebolinho',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Koper',
    'en': 'Dill',
    'de': 'Dill',
    'nl': 'Dille',
    'es': 'Eneldo',
    'fr': 'Aneth',
    'uk': 'Кріп',
    'it': 'Aneto',
    'pt': 'Endro',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Natka pietruszki',
    'en': 'Parsley',
    'de': 'Petersilie',
    'nl': 'Peterselie',
    'es': 'Perejil',
    'fr': 'Persil',
    'uk': 'Петрушка',
    'it': 'Prezzemolo',
    'pt': 'Salsa',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Kukurydza',
    'en': 'Corn',
    'de': 'Mais',
    'nl': 'Maïs',
    'es': 'Maíz',
    'fr': 'Maïs',
    'uk': 'Кукурудза',
    'it': 'Mais',
    'pt': 'Milho',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Groszek zielony',
    'en': 'Green peas',
    'de': 'Grüne Erbsen',
    'nl': 'Groene erwten',
    'es': 'Guisantes verdes',
    'fr': 'Petits pois',
    'uk': 'Зелений горошок',
    'it': 'Piselli verdi',
    'pt': 'Ervilhas verdes',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Fasolka szparagowa',
    'en': 'Green beans',
    'de': 'Grüne Bohnen',
    'nl': 'Sperziebonen',
    'es': 'Judías verdes',
    'fr': 'Haricots verts',
    'uk': 'Стручкова квасоля',
    'it': 'Fagiolini',
    'pt': 'Feijão-verde',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Pieczarki',
    'en': 'Mushrooms',
    'de': 'Champignons',
    'nl': 'Champignons',
    'es': 'Champiñones',
    'fr': 'Champignons de Paris',
    'uk': 'Печериці',
    'it': 'Funghi champignon',
    'pt': 'Cogumelos',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Papryczka chili',
    'en': 'Chili pepper',
    'de': 'Chilischote',
    'nl': 'Chilipeper',
    'es': 'Chile',
    'fr': 'Piment chili',
    'uk': 'Перець чилі',
    'it': 'Peperoncino',
    'pt': 'Pimenta chili',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Imbir',
    'en': 'Ginger',
    'de': 'Ingwer',
    'nl': 'Gember',
    'es': 'Jengibre',
    'fr': 'Gingembre',
    'uk': 'Імбир',
    'it': 'Zenzero',
    'pt': 'Gengibre',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Jarmuż',
    'en': 'Kale',
    'de': 'Grünkohl',
    'nl': 'Boerenkool',
    'es': 'Col rizada',
    'fr': 'Chou kale',
    'uk': 'Капуста кейл',
    'it': 'Cavolo riccio',
    'pt': 'Couve kale',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Bób',
    'en': 'Broad beans',
    'de': 'Saubohnen',
    'nl': 'Tuinbonen',
    'es': 'Habas',
    'fr': 'Fèves',
    'uk': 'Біб',
    'it': 'Fave',
    'pt': 'Favas',
  }),
  PredefinedItemExtraSeed(3, {
    'pl': 'Rzepa',
    'en': 'Turnip',
    'de': 'Speiserübe',
    'nl': 'Raap',
    'es': 'Nabo',
    'fr': 'Navet',
    'uk': 'Ріпа',
    'it': 'Rapa',
    'pt': 'Nabo',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Piwo ciemne',
    'en': 'Dark beer',
    'de': 'Dunkles Bier',
    'nl': 'Donker bier',
    'es': 'Cerveza negra',
    'fr': 'Bière brune',
    'uk': 'Темне пиво',
    'it': 'Birra scura',
    'pt': 'Cerveja escura',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Wino różowe',
    'en': 'Rosé wine',
    'de': 'Roséwein',
    'nl': 'Roséwijn',
    'es': 'Vino rosado',
    'fr': 'Vin rosé',
    'uk': 'Рожеве вино',
    'it': 'Vino rosato',
    'pt': 'Vinho rosé',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Wino musujące',
    'en': 'Sparkling wine',
    'de': 'Schaumwein',
    'nl': 'Mousserende wijn',
    'es': 'Vino espumoso',
    'fr': 'Vin mousseux',
    'uk': 'Ігристе вино',
    'it': 'Vino spumante',
    'pt': 'Vinho espumante',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Prosecco',
    'en': 'Prosecco',
    'de': 'Prosecco',
    'nl': 'Prosecco',
    'es': 'Prosecco',
    'fr': 'Prosecco',
    'uk': 'Просекко',
    'it': 'Prosecco',
    'pt': 'Prosecco',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Szampan',
    'en': 'Champagne',
    'de': 'Champagner',
    'nl': 'Champagne',
    'es': 'Champán',
    'fr': 'Champagne',
    'uk': 'Шампанське',
    'it': 'Champagne',
    'pt': 'Champanhe',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Rum',
    'en': 'Rum',
    'de': 'Rum',
    'nl': 'Rum',
    'es': 'Ron',
    'fr': 'Rhum',
    'uk': 'Ром',
    'it': 'Rum',
    'pt': 'Rum',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Gin',
    'en': 'Gin',
    'de': 'Gin',
    'nl': 'Gin',
    'es': 'Ginebra',
    'fr': 'Gin',
    'uk': 'Джин',
    'it': 'Gin',
    'pt': 'Gin',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Tequila',
    'en': 'Tequila',
    'de': 'Tequila',
    'nl': 'Tequila',
    'es': 'Tequila',
    'fr': 'Tequila',
    'uk': 'Текіла',
    'it': 'Tequila',
    'pt': 'Tequila',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Likier',
    'en': 'Liqueur',
    'de': 'Likör',
    'nl': 'Likeur',
    'es': 'Licor',
    'fr': 'Liqueur',
    'uk': 'Лікер',
    'it': 'Liquore',
    'pt': 'Licor',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Nalewka',
    'en': 'Infused liqueur',
    'de': 'Hauslikör',
    'nl': 'Huislikeur',
    'es': 'Licor casero',
    'fr': 'Liqueur maison',
    'uk': 'Наливка',
    'it': 'Liquore fatto in casa',
    'pt': 'Licor caseiro',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Brandy',
    'en': 'Brandy',
    'de': 'Brandy',
    'nl': 'Brandy',
    'es': 'Brandy',
    'fr': 'Brandy',
    'uk': 'Бренді',
    'it': 'Brandy',
    'pt': 'Brandy',
  }),
  PredefinedItemExtraSeed(4, {
    'pl': 'Koniak',
    'en': 'Cognac',
    'de': 'Cognac',
    'nl': 'Cognac',
    'es': 'Coñac',
    'fr': 'Cognac',
    'uk': 'Коньяк',
    'it': 'Cognac',
    'pt': 'Conhaque',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Margaryna',
    'en': 'Margarine',
    'de': 'Margarine',
    'nl': 'Margarine',
    'es': 'Margarina',
    'fr': 'Margarine',
    'uk': 'Маргарин',
    'it': 'Margarina',
    'pt': 'Margarina',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Ser biały',
    'en': 'White cheese',
    'de': 'Weißkäse',
    'nl': 'Witte kaas',
    'es': 'Queso blanco',
    'fr': 'Fromage blanc',
    'uk': 'Білий сир',
    'it': 'Formaggio bianco',
    'pt': 'Queijo branco',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Serek wiejski',
    'en': 'Cottage cheese',
    'de': 'Hüttenkäse',
    'nl': 'Hüttenkäse',
    'es': 'Queso cottage',
    'fr': 'Fromage cottage',
    'uk': 'Зернистий сир',
    'it': 'Fiocchi di latte',
    'pt': 'Queijo cottage',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Serek śmietankowy',
    'en': 'Cream cheese',
    'de': 'Frischkäse',
    'nl': 'Roomkaas',
    'es': 'Queso crema',
    'fr': 'Fromage frais',
    'uk': 'Вершковий сир',
    'it': 'Formaggio cremoso',
    'pt': 'Queijo creme',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Feta',
    'en': 'Feta',
    'de': 'Feta',
    'nl': 'Feta',
    'es': 'Feta',
    'fr': 'Feta',
    'uk': 'Фета',
    'it': 'Feta',
    'pt': 'Feta',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Parmezan',
    'en': 'Parmesan',
    'de': 'Parmesan',
    'nl': 'Parmezaan',
    'es': 'Parmesano',
    'fr': 'Parmesan',
    'uk': 'Пармезан',
    'it': 'Parmigiano',
    'pt': 'Parmesão',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Ser pleśniowy',
    'en': 'Blue cheese',
    'de': 'Blauschimmelkäse',
    'nl': 'Blauwschimmelkaas',
    'es': 'Queso azul',
    'fr': 'Fromage bleu',
    'uk': 'Сир з пліснявою',
    'it': 'Formaggio erborinato',
    'pt': 'Queijo azul',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Ser kozi',
    'en': 'Goat cheese',
    'de': 'Ziegenkäse',
    'nl': 'Geitenkaas',
    'es': 'Queso de cabra',
    'fr': 'Fromage de chèvre',
    'uk': 'Козячий сир',
    'it': 'Formaggio di capra',
    'pt': 'Queijo de cabra',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Deser mleczny',
    'en': 'Dairy dessert',
    'de': 'Milchdessert',
    'nl': 'Zuiveldessert',
    'es': 'Postre lácteo',
    'fr': 'Dessert lacté',
    'uk': 'Молочний десерт',
    'it': 'Dessert al latte',
    'pt': 'Sobremesa láctea',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Bita śmietana',
    'en': 'Whipped cream',
    'de': 'Schlagsahne',
    'nl': 'Slagroom',
    'es': 'Nata montada',
    'fr': 'Crème fouettée',
    'uk': 'Збиті вершки',
    'it': 'Panna montata',
    'pt': 'Natas batidas',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Mleko skondensowane',
    'en': 'Condensed milk',
    'de': 'Kondensmilch',
    'nl': 'Gecondenseerde melk',
    'es': 'Leche condensada',
    'fr': 'Lait concentré',
    'uk': 'Згущене молоко',
    'it': 'Latte condensato',
    'pt': 'Leite condensado',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Skyr',
    'en': 'Skyr',
    'de': 'Skyr',
    'nl': 'Skyr',
    'es': 'Skyr',
    'fr': 'Skyr',
    'uk': 'Скир',
    'it': 'Skyr',
    'pt': 'Skyr',
  }),
  PredefinedItemExtraSeed(5, {
    'pl': 'Śmietanka do kawy',
    'en': 'Coffee cream',
    'de': 'Kaffeesahne',
    'nl': 'Koffieroom',
    'es': 'Crema para café',
    'fr': 'Crème à café',
    'uk': 'Вершки для кави',
    'it': 'Panna da caffè',
    'pt': 'Natas para café',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Bułka grahamka',
    'en': 'Wholemeal roll',
    'de': 'Grahambrötchen',
    'nl': 'Volkorenbroodje',
    'es': 'Panecillo integral',
    'fr': 'Petit pain complet',
    'uk': 'Цільнозернова булочка',
    'it': 'Panino integrale',
    'pt': 'Pão integral pequeno',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Ciabatta',
    'en': 'Ciabatta',
    'de': 'Ciabatta',
    'nl': 'Ciabatta',
    'es': 'Ciabatta',
    'fr': 'Ciabatta',
    'uk': 'Чіабата',
    'it': 'Ciabatta',
    'pt': 'Ciabatta',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Bułka hamburgerowa',
    'en': 'Burger bun',
    'de': 'Hamburgerbrötchen',
    'nl': 'Hamburgerbroodje',
    'es': 'Pan de hamburguesa',
    'fr': 'Pain à burger',
    'uk': 'Булочка для бургера',
    'it': 'Panino per hamburger',
    'pt': 'Pão de hambúrguer',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Bułka hot dog',
    'en': 'Hot dog bun',
    'de': 'Hot-Dog-Brötchen',
    'nl': 'Hotdogbroodje',
    'es': 'Pan de perrito caliente',
    'fr': 'Pain à hot-dog',
    'uk': 'Булочка для хот-дога',
    'it': 'Panino per hot dog',
    'pt': 'Pão de cachorro-quente',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Pita',
    'en': 'Pita bread',
    'de': 'Pitabrot',
    'nl': 'Pitabrood',
    'es': 'Pan de pita',
    'fr': 'Pain pita',
    'uk': 'Піта',
    'it': 'Pane pita',
    'pt': 'Pão pita',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Rogal',
    'en': 'Crescent roll',
    'de': 'Hörnchen',
    'nl': 'Halvemaanbroodje',
    'es': 'Bollo en media luna',
    'fr': 'Petit pain croissant',
    'uk': 'Рогалик',
    'it': 'Cornetto',
    'pt': 'Pão em meia-lua',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Drożdżówka',
    'en': 'Sweet yeast bun',
    'de': 'Hefegebäck',
    'nl': 'Zoet gistbroodje',
    'es': 'Bollo de levadura',
    'fr': 'Brioche sucrée',
    'uk': 'Солодка дріжджова булочка',
    'it': 'Dolce lievitato',
    'pt': 'Pão doce levedado',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Muffin',
    'en': 'Muffin',
    'de': 'Muffin',
    'nl': 'Muffin',
    'es': 'Muffin',
    'fr': 'Muffin',
    'uk': 'Маффін',
    'it': 'Muffin',
    'pt': 'Muffin',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Placek',
    'en': 'Tray cake',
    'de': 'Blechkuchen',
    'nl': 'Plaatcake',
    'es': 'Bizcocho',
    'fr': 'Gâteau',
    'uk': 'Пиріг',
    'it': 'Torta',
    'pt': 'Bolo',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Ciasto',
    'en': 'Cake',
    'de': 'Kuchen',
    'nl': 'Taart',
    'es': 'Pastel',
    'fr': 'Gâteau',
    'uk': 'Торт',
    'it': 'Torta',
    'pt': 'Bolo',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Precel',
    'en': 'Pretzel',
    'de': 'Brezel',
    'nl': 'Pretzel',
    'es': 'Pretzel',
    'fr': 'Bretzel',
    'uk': 'Крендель',
    'it': 'Pretzel',
    'pt': 'Pretzel',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Sucharki',
    'en': 'Rusks',
    'de': 'Zwieback',
    'nl': 'Beschuit',
    'es': 'Biscotes',
    'fr': 'Biscottes',
    'uk': 'Сухарі',
    'it': 'Fette biscottate',
    'pt': 'Tostas',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Podpłomyk',
    'en': 'Flatbread',
    'de': 'Fladenbrot',
    'nl': 'Platbrood',
    'es': 'Pan plano',
    'fr': 'Pain plat',
    'uk': 'Плаский хліб',
    'it': 'Pane piatto',
    'pt': 'Pão achatado',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Chleb bezglutenowy',
    'en': 'Gluten-free bread',
    'de': 'Glutenfreies Brot',
    'nl': 'Glutenvrij brood',
    'es': 'Pan sin gluten',
    'fr': 'Pain sans gluten',
    'uk': 'Безглютеновий хліб',
    'it': 'Pane senza glutine',
    'pt': 'Pão sem glúten',
  }),
  PredefinedItemExtraSeed(6, {
    'pl': 'Paluch chlebowy',
    'en': 'Breadstick',
    'de': 'Brotstange',
    'nl': 'Broodstengel',
    'es': 'Palito de pan',
    'fr': 'Gressin',
    'uk': 'Хлібна паличка',
    'it': 'Grissino',
    'pt': 'Pão em palito',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Udko z kurczaka',
    'en': 'Chicken leg',
    'de': 'Hähnchenschenkel',
    'nl': 'Kippenbout',
    'es': 'Muslo de pollo',
    'fr': 'Cuisse de poulet',
    'uk': 'Куряче стегенце',
    'it': 'Coscia di pollo',
    'pt': 'Coxa de frango',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Skrzydełka z kurczaka',
    'en': 'Chicken wings',
    'de': 'Hähnchenflügel',
    'nl': 'Kippenvleugels',
    'es': 'Alitas de pollo',
    'fr': 'Ailes de poulet',
    'uk': 'Курячі крильця',
    'it': 'Alette di pollo',
    'pt': 'Asas de frango',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Podudzie z indyka',
    'en': 'Turkey drumstick',
    'de': 'Putenunterkeule',
    'nl': 'Kalkoendrumstick',
    'es': 'Muslo de pavo',
    'fr': 'Pilon de dinde',
    'uk': 'Гомілка індички',
    'it': 'Fuso di tacchino',
    'pt': 'Perna de peru',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Karkówka',
    'en': 'Pork neck',
    'de': 'Schweinenacken',
    'nl': 'Varkensnek',
    'es': 'Cabecero de cerdo',
    'fr': 'Échine de porc',
    'uk': 'Свиняча шийка',
    'it': 'Coppa di maiale',
    'pt': 'Cachaço de porco',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Żeberka',
    'en': 'Ribs',
    'de': 'Rippchen',
    'nl': 'Ribbetjes',
    'es': 'Costillas',
    'fr': 'Côtes levées',
    'uk': 'Реберця',
    'it': 'Costine',
    'pt': 'Entrecosto',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Parówki',
    'en': 'Wieners',
    'de': 'Würstchen',
    'nl': 'Knakworsten',
    'es': 'Salchichas',
    'fr': 'Saucisses de Francfort',
    'uk': 'Сосиски',
    'it': 'Würstel',
    'pt': 'Salsichas',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Frankfurterki',
    'en': 'Frankfurters',
    'de': 'Frankfurter',
    'nl': 'Frankfurters',
    'es': 'Frankfurts',
    'fr': 'Frankfurters',
    'uk': 'Франкфуртські сосиски',
    'it': 'Frankfurter',
    'pt': 'Frankfurters',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Mortadela',
    'en': 'Mortadella',
    'de': 'Mortadella',
    'nl': 'Mortadella',
    'es': 'Mortadela',
    'fr': 'Mortadelle',
    'uk': 'Мортадела',
    'it': 'Mortadella',
    'pt': 'Mortadela',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Pasztet',
    'en': 'Pâté',
    'de': 'Pastete',
    'nl': 'Paté',
    'es': 'Paté',
    'fr': 'Pâté',
    'uk': 'Паштет',
    'it': 'Paté',
    'pt': 'Patê',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Wołowina',
    'en': 'Beef',
    'de': 'Rindfleisch',
    'nl': 'Rundvlees',
    'es': 'Ternera',
    'fr': 'Bœuf',
    'uk': 'Яловичина',
    'it': 'Manzo',
    'pt': 'Vaca',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Cielęcina',
    'en': 'Veal',
    'de': 'Kalbfleisch',
    'nl': 'Kalfsvlees',
    'es': 'Ternera lechal',
    'fr': 'Veau',
    'uk': 'Телятина',
    'it': 'Vitello',
    'pt': 'Vitela',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Jagnięcina',
    'en': 'Lamb',
    'de': 'Lammfleisch',
    'nl': 'Lamsvlees',
    'es': 'Cordero',
    'fr': 'Agneau',
    'uk': 'Ягнятина',
    'it': 'Agnello',
    'pt': 'Borrego',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Kaczka',
    'en': 'Duck',
    'de': 'Ente',
    'nl': 'Eend',
    'es': 'Pato',
    'fr': 'Canard',
    'uk': 'Качка',
    'it': 'Anatra',
    'pt': 'Pato',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Gęś',
    'en': 'Goose',
    'de': 'Gans',
    'nl': 'Gans',
    'es': 'Oca',
    'fr': 'Oie',
    'uk': 'Гуска',
    'it': 'Oca',
    'pt': 'Ganso',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Śledź',
    'en': 'Herring',
    'de': 'Hering',
    'nl': 'Haring',
    'es': 'Arenque',
    'fr': 'Hareng',
    'uk': 'Оселедець',
    'it': 'Aringa',
    'pt': 'Arenque',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Makrela',
    'en': 'Mackerel',
    'de': 'Makrele',
    'nl': 'Makreel',
    'es': 'Caballa',
    'fr': 'Maquereau',
    'uk': 'Скумбрія',
    'it': 'Sgombro',
    'pt': 'Cavala',
  }),
  PredefinedItemExtraSeed(7, {
    'pl': 'Paluszki rybne',
    'en': 'Fish fingers',
    'de': 'Fischstäbchen',
    'nl': 'Vissticks',
    'es': 'Palitos de pescado',
    'fr': 'Bâtonnets de poisson',
    'uk': 'Рибні палички',
    'it': 'Bastoncini di pesce',
    'pt': 'Douradinhos',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Mieszanka warzywna mrożona',
    'en': 'Frozen vegetable mix',
    'de': 'Tiefkühlgemüsemischung',
    'nl': 'Diepvriesgroentemix',
    'es': 'Mezcla de verduras congeladas',
    'fr': 'Mélange de légumes surgelés',
    'uk': 'Заморожена овочева суміш',
    'it': 'Misto di verdure surgelate',
    'pt': 'Mistura de legumes congelados',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Uszka mrożone',
    'en': 'Frozen mini dumplings',
    'de': 'Tiefgekühlte Mini-Teigtaschen',
    'nl': 'Diepvries mini-dumplings',
    'es': 'Mini empanadillas congeladas',
    'fr': 'Petits raviolis surgelés',
    'uk': 'Заморожені вушка',
    'it': 'Mini ravioli surgelati',
    'pt': 'Mini dumplings congelados',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Nuggetsy mrożone',
    'en': 'Frozen nuggets',
    'de': 'Tiefkühlnuggets',
    'nl': 'Diepvriesnuggets',
    'es': 'Nuggets congelados',
    'fr': 'Nuggets surgelés',
    'uk': 'Заморожені нагетси',
    'it': 'Nuggets surgelati',
    'pt': 'Nuggets congelados',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Lody czekoladowe',
    'en': 'Chocolate ice cream',
    'de': 'Schokoladeneis',
    'nl': 'Chocolade-ijs',
    'es': 'Helado de chocolate',
    'fr': 'Glace au chocolat',
    'uk': 'Шоколадне морозиво',
    'it': 'Gelato al cioccolato',
    'pt': 'Gelado de chocolate',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Lody truskawkowe',
    'en': 'Strawberry ice cream',
    'de': 'Erdbeereis',
    'nl': 'Aardbeienijs',
    'es': 'Helado de fresa',
    'fr': 'Glace à la fraise',
    'uk': 'Полуничне морозиво',
    'it': 'Gelato alla fragola',
    'pt': 'Gelado de morango',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Sorbet',
    'en': 'Sorbet',
    'de': 'Sorbet',
    'nl': 'Sorbet',
    'es': 'Sorbete',
    'fr': 'Sorbet',
    'uk': 'Сорбет',
    'it': 'Sorbetto',
    'pt': 'Sorvete',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Szpinak mrożony',
    'en': 'Frozen spinach',
    'de': 'Tiefkühlspinat',
    'nl': 'Diepvriesspinazie',
    'es': 'Espinacas congeladas',
    'fr': 'Épinards surgelés',
    'uk': 'Заморожений шпинат',
    'it': 'Spinaci surgelati',
    'pt': 'Espinafres congelados',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Fasolka mrożona',
    'en': 'Frozen green beans',
    'de': 'Tiefkühlbohnen',
    'nl': 'Diepvries sperziebonen',
    'es': 'Judías verdes congeladas',
    'fr': 'Haricots verts surgelés',
    'uk': 'Заморожена стручкова квасоля',
    'it': 'Fagiolini surgelati',
    'pt': 'Feijão-verde congelado',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Krewetki mrożone',
    'en': 'Frozen shrimp',
    'de': 'Tiefkühlgarnelen',
    'nl': 'Diepvriesgarnalen',
    'es': 'Gambas congeladas',
    'fr': 'Crevettes surgelées',
    'uk': 'Заморожені креветки',
    'it': 'Gamberi surgelati',
    'pt': 'Camarão congelado',
  }),
  PredefinedItemExtraSeed(8, {
    'pl': 'Ciasto francuskie mrożone',
    'en': 'Frozen puff pastry',
    'de': 'Tiefgekühlter Blätterteig',
    'nl': 'Diepvries bladerdeeg',
    'es': 'Masa de hojaldre congelada',
    'fr': 'Pâte feuilletée surgelée',
    'uk': 'Заморожене листкове тісто',
    'it': 'Pasta sfoglia surgelata',
    'pt': 'Massa folhada congelada',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Sól do zmywarki',
    'en': 'Dishwasher salt',
    'de': 'Spülmaschinensalz',
    'nl': 'Vaatwaszout',
    'es': 'Sal para lavavajillas',
    'fr': 'Sel pour lave-vaisselle',
    'uk': 'Сіль для посудомийної машини',
    'it': 'Sale per lavastoviglie',
    'pt': 'Sal para máquina da loiça',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Nabłyszczacz do zmywarki',
    'en': 'Rinse aid',
    'de': 'Klarspüler',
    'nl': 'Glansspoelmiddel',
    'es': 'Abrillantador',
    'fr': 'Liquide de rinçage',
    'uk': 'Ополіскувач для посудомийної машини',
    'it': 'Brillantante',
    'pt': 'Abrilhantador',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Płyn do prania',
    'en': 'Laundry liquid',
    'de': 'Flüssigwaschmittel',
    'nl': 'Vloeibaar wasmiddel',
    'es': 'Detergente líquido',
    'fr': 'Lessive liquide',
    'uk': 'Рідкий засіб для прання',
    'it': 'Detersivo liquido',
    'pt': 'Detergente líquido',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Odplamiacz',
    'en': 'Stain remover',
    'de': 'Fleckenentferner',
    'nl': 'Vlekverwijderaar',
    'es': 'Quitamanchas',
    'fr': 'Détachant',
    'uk': 'Плямовивідник',
    'it': 'Smacchiatore',
    'pt': 'Tira-nódoas',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Odżywka do włosów',
    'en': 'Conditioner',
    'de': 'Spülung',
    'nl': 'Conditioner',
    'es': 'Acondicionador',
    'fr': 'Après-shampoing',
    'uk': 'Кондиціонер для волосся',
    'it': 'Balsamo',
    'pt': 'Amaciador de cabelo',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Żel pod prysznic',
    'en': 'Shower gel',
    'de': 'Duschgel',
    'nl': 'Douchegel',
    'es': 'Gel de ducha',
    'fr': 'Gel douche',
    'uk': 'Гель для душу',
    'it': 'Bagnodoccia',
    'pt': 'Gel de banho',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Chusteczki nawilżane',
    'en': 'Wet wipes',
    'de': 'Feuchttücher',
    'nl': 'Vochtige doekjes',
    'es': 'Toallitas húmedas',
    'fr': 'Lingettes humides',
    'uk': 'Вологі серветки',
    'it': 'Salviette umidificate',
    'pt': 'Toalhitas húmidas',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Gąbka do naczyń',
    'en': 'Dish sponge',
    'de': 'Spülschwamm',
    'nl': 'Afwasspons',
    'es': 'Esponja para platos',
    'fr': 'Éponge à vaisselle',
    'uk': 'Губка для посуду',
    'it': 'Spugna per piatti',
    'pt': 'Esponja da loiça',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Ściereczka',
    'en': 'Cleaning cloth',
    'de': 'Putztuch',
    'nl': 'Schoonmaakdoekje',
    'es': 'Paño de limpieza',
    'fr': 'Chiffon de nettoyage',
    'uk': 'Ганчірка',
    'it': 'Panno per pulizie',
    'pt': 'Pano de limpeza',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Folia aluminiowa',
    'en': 'Aluminum foil',
    'de': 'Alufolie',
    'nl': 'Aluminiumfolie',
    'es': 'Papel de aluminio',
    'fr': 'Papier aluminium',
    'uk': 'Алюмінієва фольга',
    'it': 'Carta stagnola',
    'pt': 'Folha de alumínio',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Folia spożywcza',
    'en': 'Cling film',
    'de': 'Frischhaltefolie',
    'nl': 'Vershoudfolie',
    'es': 'Film transparente',
    'fr': 'Film alimentaire',
    'uk': 'Харчова плівка',
    'it': 'Pellicola alimentare',
    'pt': 'Película aderente',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Papier do pieczenia',
    'en': 'Baking paper',
    'de': 'Backpapier',
    'nl': 'Bakpapier',
    'es': 'Papel de hornear',
    'fr': 'Papier cuisson',
    'uk': 'Папір для випічки',
    'it': 'Carta da forno',
    'pt': 'Papel vegetal',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Rękawiczki jednorazowe',
    'en': 'Disposable gloves',
    'de': 'Einweghandschuhe',
    'nl': 'Wegwerphandschoenen',
    'es': 'Guantes desechables',
    'fr': 'Gants jetables',
    'uk': 'Одноразові рукавички',
    'it': 'Guanti monouso',
    'pt': 'Luvas descartáveis',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Środek do szyb',
    'en': 'Glass cleaner',
    'de': 'Glasreiniger',
    'nl': 'Glasreiniger',
    'es': 'Limpiacristales',
    'fr': 'Nettoyant vitres',
    'uk': 'Засіб для скла',
    'it': 'Detergente per vetri',
    'pt': 'Limpa-vidros',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Środek do łazienki',
    'en': 'Bathroom cleaner',
    'de': 'Badreiniger',
    'nl': 'Badkamerreiniger',
    'es': 'Limpiador de baño',
    'fr': 'Nettoyant salle de bain',
    'uk': 'Засіб для ванної кімнати',
    'it': 'Detergente bagno',
    'pt': 'Limpa-casas de banho',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Środek do kuchni',
    'en': 'Kitchen cleaner',
    'de': 'Küchenreiniger',
    'nl': 'Keukenreiniger',
    'es': 'Limpiador de cocina',
    'fr': 'Nettoyant cuisine',
    'uk': 'Засіб для кухні',
    'it': 'Detergente cucina',
    'pt': 'Limpa-cozinhas',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Płyn do podłóg',
    'en': 'Floor cleaner',
    'de': 'Bodenreiniger',
    'nl': 'Vloerreiniger',
    'es': 'Limpiador de suelos',
    'fr': 'Nettoyant sols',
    'uk': 'Засіб для підлоги',
    'it': 'Detergente per pavimenti',
    'pt': 'Detergente para pavimentos',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Odświeżacz powietrza',
    'en': 'Air freshener',
    'de': 'Lufterfrischer',
    'nl': 'Luchtverfrisser',
    'es': 'Ambientador',
    'fr': 'Désodorisant',
    'uk': 'Освіжувач повітря',
    'it': 'Deodorante per ambienti',
    'pt': 'Ambientador',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Maszynka do golenia',
    'en': 'Razor',
    'de': 'Rasierer',
    'nl': 'Scheermes',
    'es': 'Maquinilla de afeitar',
    'fr': 'Rasoir',
    'uk': 'Бритва',
    'it': 'Rasoio',
    'pt': 'Máquina de barbear',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Płatki kosmetyczne',
    'en': 'Cotton pads',
    'de': 'Wattepads',
    'nl': 'Wattenschijfjes',
    'es': 'Discos de algodón',
    'fr': 'Cotons démaquillants',
    'uk': 'Ватні диски',
    'it': 'Dischetti di cotone',
    'pt': 'Discos de algodão',
  }),
  PredefinedItemExtraSeed(9, {
    'pl': 'Patyczki higieniczne',
    'en': 'Cotton swabs',
    'de': 'Wattestäbchen',
    'nl': 'Wattenstaafjes',
    'es': 'Bastoncillos de algodón',
    'fr': 'Cotons-tiges',
    'uk': 'Ватні палички',
    'it': 'Cotton fioc',
    'pt': 'Cotonetes',
  }),
];
