import 'l10n/app_localizations.dart';
import 'models.dart';
import 'predefined_items_extra.dart';

const int predefinedItemSeedVersion = 2;

class _PredefinedItemSeed {
  const _PredefinedItemSeed(this.categoryIndex, this.names);

  final int categoryIndex;
  final Map<String, String> names;
}

List<RememberedItemCategory> predefinedItemMemoryForLanguageCode(
  String languageCode, {
  List<String>? availableCategories,
}) {
  final resolvedCategories = <int, String>{};

  for (var index = 0; index < defaultCategories.length; index++) {
    if (availableCategories == null) {
      resolvedCategories[index] =
          AppLocalizations.defaultCategoriesForLanguageCode(languageCode)[index];
      continue;
    }

    final resolvedCategory = _resolveAvailableCategoryForIndex(
      index,
      availableCategories,
    );
    if (resolvedCategory != null) {
      resolvedCategories[index] = resolvedCategory;
    }
  }

  final seededItems = <RememberedItemCategory>[];
  final seenItemKeys = <String>{};

  for (final seed in _allPredefinedItemSeeds()) {
    final category = resolvedCategories[seed.categoryIndex];
    if (category == null) {
      continue;
    }

    final itemName =
        seed.names[languageCode] ?? seed.names['pl'] ?? seed.names['en'];
    if (itemName == null || itemName.trim().isEmpty) {
      continue;
    }

    final normalizedItemKey = normalizeLatinText(itemName);
    if (normalizedItemKey.isEmpty || !seenItemKeys.add(normalizedItemKey)) {
      continue;
    }

    seededItems.add(
      RememberedItemCategory(
        itemName: itemName,
        category: category,
      ),
    );
  }

  return seededItems;
}

String? _resolveAvailableCategoryForIndex(
  int index,
  List<String> availableCategories,
) {
  final categoryVariants = <String>{
    defaultCategories[index],
  };

  for (final locale in AppLocalizations.supportedLocales) {
    categoryVariants.add(
      AppLocalizations.defaultCategoriesForLanguageCode(locale.languageCode)[index],
    );
  }

  for (final availableCategory in availableCategories) {
    for (final variant in categoryVariants) {
      if (sameNormalizedText(availableCategory, variant)) {
        return availableCategory;
      }
    }
  }

  return null;
}

Iterable<_PredefinedItemSeed> _allPredefinedItemSeeds() sync* {
  yield* _predefinedItemSeeds;
  for (final seed in predefinedItemExtraSeeds) {
    yield _PredefinedItemSeed(seed.categoryIndex, seed.names);
  }
}

const List<_PredefinedItemSeed> _predefinedItemSeeds = [
  // Drinks
  _PredefinedItemSeed(0, {
    'en': 'Still water',
    'pl': 'Woda niegazowana',
    'de': 'Stilles Wasser',
    'nl': 'Plat water',
    'es': 'Agua sin gas',
    'fr': 'Eau plate',
    'uk': 'Негазована вода',
    'it': 'Acqua naturale',
    'pt': 'Água sem gás',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Sparkling water',
    'pl': 'Woda gazowana',
    'de': 'Sprudelwasser',
    'nl': 'Bruiswater',
    'es': 'Agua con gas',
    'fr': 'Eau gazeuse',
    'uk': 'Газована вода',
    'it': 'Acqua frizzante',
    'pt': 'Água com gás',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Cola',
    'pl': 'Cola',
    'de': 'Cola',
    'nl': 'Cola',
    'es': 'Cola',
    'fr': 'Cola',
    'uk': 'Кола',
    'it': 'Cola',
    'pt': 'Cola',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Lemonade',
    'pl': 'Lemoniada',
    'de': 'Limonade',
    'nl': 'Limonade',
    'es': 'Limonada',
    'fr': 'Limonade',
    'uk': 'Лимонад',
    'it': 'Limonata',
    'pt': 'Limonada',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Orange juice',
    'pl': 'Sok pomarańczowy',
    'de': 'Orangensaft',
    'nl': 'Sinaasappelsap',
    'es': 'Zumo de naranja',
    'fr': "Jus d'orange",
    'uk': 'Апельсиновий сік',
    'it': 'Succo d’arancia',
    'pt': 'Sumo de laranja',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Apple juice',
    'pl': 'Sok jabłkowy',
    'de': 'Apfelsaft',
    'nl': 'Appelsap',
    'es': 'Zumo de manzana',
    'fr': 'Jus de pomme',
    'uk': 'Яблучний сік',
    'it': 'Succo di mela',
    'pt': 'Sumo de maçã',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Ground coffee',
    'pl': 'Kawa mielona',
    'de': 'Gemahlener Kaffee',
    'nl': 'Gemalen koffie',
    'es': 'Café molido',
    'fr': 'Café moulu',
    'uk': 'Мелена кава',
    'it': 'Caffè macinato',
    'pt': 'Café moído',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Instant coffee',
    'pl': 'Kawa rozpuszczalna',
    'de': 'Instantkaffee',
    'nl': 'Oploskoffie',
    'es': 'Café soluble',
    'fr': 'Café instantané',
    'uk': 'Розчинна кава',
    'it': 'Caffè solubile',
    'pt': 'Café solúvel',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Black tea',
    'pl': 'Herbata czarna',
    'de': 'Schwarzer Tee',
    'nl': 'Zwarte thee',
    'es': 'Té negro',
    'fr': 'Thé noir',
    'uk': 'Чорний чай',
    'it': 'Tè nero',
    'pt': 'Chá preto',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Green tea',
    'pl': 'Herbata zielona',
    'de': 'Grüner Tee',
    'nl': 'Groene thee',
    'es': 'Té verde',
    'fr': 'Thé vert',
    'uk': 'Зелений чай',
    'it': 'Tè verde',
    'pt': 'Chá verde',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Cocoa',
    'pl': 'Kakao',
    'de': 'Kakao',
    'nl': 'Cacao',
    'es': 'Cacao',
    'fr': 'Cacao',
    'uk': 'Какао',
    'it': 'Cacao',
    'pt': 'Cacau',
  }),
  _PredefinedItemSeed(0, {
    'en': 'Oat milk',
    'pl': 'Mleko owsiane',
    'de': 'Hafermilch',
    'nl': 'Havermelk',
    'es': 'Leche de avena',
    'fr': 'Lait d’avoine',
    'uk': 'Вівсяне молоко',
    'it': 'Latte d’avena',
    'pt': 'Leite de aveia',
  }),

  // Sweets
  _PredefinedItemSeed(1, {
    'en': 'Milk chocolate',
    'pl': 'Czekolada mleczna',
    'de': 'Milchschokolade',
    'nl': 'Melkchocolade',
    'es': 'Chocolate con leche',
    'fr': 'Chocolat au lait',
    'uk': 'Молочний шоколад',
    'it': 'Cioccolato al latte',
    'pt': 'Chocolate de leite',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Dark chocolate',
    'pl': 'Czekolada gorzka',
    'de': 'Zartbitterschokolade',
    'nl': 'Pure chocolade',
    'es': 'Chocolate negro',
    'fr': 'Chocolat noir',
    'uk': 'Чорний шоколад',
    'it': 'Cioccolato fondente',
    'pt': 'Chocolate negro',
  }),
  _PredefinedItemSeed(1, {
    'en': 'White chocolate',
    'pl': 'Czekolada biała',
    'de': 'Weiße Schokolade',
    'nl': 'Witte chocolade',
    'es': 'Chocolate blanco',
    'fr': 'Chocolat blanc',
    'uk': 'Білий шоколад',
    'it': 'Cioccolato bianco',
    'pt': 'Chocolate branco',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Chocolate bar',
    'pl': 'Baton czekoladowy',
    'de': 'Schokoriegel',
    'nl': 'Chocoladereep',
    'es': 'Barrita de chocolate',
    'fr': 'Barre chocolatée',
    'uk': 'Шоколадний батончик',
    'it': 'Barretta di cioccolato',
    'pt': 'Barra de chocolate',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Wafer',
    'pl': 'Wafel',
    'de': 'Waffel',
    'nl': 'Wafel',
    'es': 'Barquillo',
    'fr': 'Gaufrette',
    'uk': 'Вафля',
    'it': 'Wafer',
    'pt': 'Wafer',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Biscuits',
    'pl': 'Herbatniki',
    'de': 'Kekse',
    'nl': 'Biscuits',
    'es': 'Galletas tipo biscuit',
    'fr': 'Biscuits',
    'uk': 'Печиво',
    'it': 'Biscotti secchi',
    'pt': 'Bolachas',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Cookies',
    'pl': 'Ciastka',
    'de': 'Plätzchen',
    'nl': 'Koekjes',
    'es': 'Galletas',
    'fr': 'Cookies',
    'uk': 'Печиво',
    'it': 'Biscotti',
    'pt': 'Cookies',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Crackers',
    'pl': 'Krakersy',
    'de': 'Cracker',
    'nl': 'Crackers',
    'es': 'Crackers',
    'fr': 'Crackers',
    'uk': 'Крекери',
    'it': 'Cracker',
    'pt': 'Crackers',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Potato chips',
    'pl': 'Chipsy ziemniaczane',
    'de': 'Kartoffelchips',
    'nl': 'Aardappelchips',
    'es': 'Patatas fritas',
    'fr': 'Chips de pommes de terre',
    'uk': 'Картопляні чіпси',
    'it': 'Patatine',
    'pt': 'Batatas fritas',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Popcorn',
    'pl': 'Popcorn',
    'de': 'Popcorn',
    'nl': 'Popcorn',
    'es': 'Palomitas',
    'fr': 'Pop-corn',
    'uk': 'Попкорн',
    'it': 'Popcorn',
    'pt': 'Pipocas',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Gummies',
    'pl': 'Żelki',
    'de': 'Gummibärchen',
    'nl': 'Gumsnoep',
    'es': 'Gominolas',
    'fr': 'Bonbons gélifiés',
    'uk': 'Желейки',
    'it': 'Caramelle gommose',
    'pt': 'Gomas',
  }),
  _PredefinedItemSeed(1, {
    'en': 'Chocolate spread',
    'pl': 'Krem czekoladowy',
    'de': 'Schokocreme',
    'nl': 'Chocopasta',
    'es': 'Crema de cacao',
    'fr': 'Pâte à tartiner au chocolat',
    'uk': 'Шоколадна паста',
    'it': 'Crema al cioccolato',
    'pt': 'Creme de chocolate',
  }),

  // Fruits
  _PredefinedItemSeed(2, {
    'en': 'Apple',
    'pl': 'Jabłko',
    'de': 'Apfel',
    'nl': 'Appel',
    'es': 'Manzana',
    'fr': 'Pomme',
    'uk': 'Яблуко',
    'it': 'Mela',
    'pt': 'Maçã',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Banana',
    'pl': 'Banan',
    'de': 'Banane',
    'nl': 'Banaan',
    'es': 'Banana',
    'fr': 'Banane',
    'uk': 'Банан',
    'it': 'Banana',
    'pt': 'Banana',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Orange',
    'pl': 'Pomarańcza',
    'de': 'Orange',
    'nl': 'Sinaasappel',
    'es': 'Naranja',
    'fr': 'Orange',
    'uk': 'Апельсин',
    'it': 'Arancia',
    'pt': 'Laranja',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Tangerine',
    'pl': 'Mandarynka',
    'de': 'Mandarine',
    'nl': 'Mandarijn',
    'es': 'Mandarina',
    'fr': 'Mandarine',
    'uk': 'Мандарин',
    'it': 'Mandarino',
    'pt': 'Tangerina',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Lemon',
    'pl': 'Cytryna',
    'de': 'Zitrone',
    'nl': 'Citroen',
    'es': 'Limón',
    'fr': 'Citron',
    'uk': 'Лимон',
    'it': 'Limone',
    'pt': 'Limão',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Grapefruit',
    'pl': 'Grejpfrut',
    'de': 'Grapefruit',
    'nl': 'Grapefruit',
    'es': 'Pomelo',
    'fr': 'Pamplemousse',
    'uk': 'Грейпфрут',
    'it': 'Pompelmo',
    'pt': 'Toranja',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Pear',
    'pl': 'Gruszka',
    'de': 'Birne',
    'nl': 'Peer',
    'es': 'Pera',
    'fr': 'Poire',
    'uk': 'Груша',
    'it': 'Pera',
    'pt': 'Pêra',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Plum',
    'pl': 'Śliwka',
    'de': 'Pflaume',
    'nl': 'Pruim',
    'es': 'Ciruela',
    'fr': 'Prune',
    'uk': 'Слива',
    'it': 'Prugna',
    'pt': 'Ameixa',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Peach',
    'pl': 'Brzoskwinia',
    'de': 'Pfirsich',
    'nl': 'Perzik',
    'es': 'Melocotón',
    'fr': 'Pêche',
    'uk': 'Персик',
    'it': 'Pesca',
    'pt': 'Pêssego',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Grapes',
    'pl': 'Winogrona',
    'de': 'Trauben',
    'nl': 'Druiven',
    'es': 'Uvas',
    'fr': 'Raisins',
    'uk': 'Виноград',
    'it': 'Uva',
    'pt': 'Uvas',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Strawberry',
    'pl': 'Truskawka',
    'de': 'Erdbeere',
    'nl': 'Aardbei',
    'es': 'Fresa',
    'fr': 'Fraise',
    'uk': 'Полуниця',
    'it': 'Fragola',
    'pt': 'Morango',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Blueberry',
    'pl': 'Borówka',
    'de': 'Heidelbeere',
    'nl': 'Bosbes',
    'es': 'Arándano',
    'fr': 'Myrtille',
    'uk': 'Лохина',
    'it': 'Mirtillo',
    'pt': 'Mirtilo',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Kiwi',
    'pl': 'Kiwi',
    'de': 'Kiwi',
    'nl': 'Kiwi',
    'es': 'Kiwi',
    'fr': 'Kiwi',
    'uk': 'Ківі',
    'it': 'Kiwi',
    'pt': 'Kiwi',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Pineapple',
    'pl': 'Ananas',
    'de': 'Ananas',
    'nl': 'Ananas',
    'es': 'Piña',
    'fr': 'Ananas',
    'uk': 'Ананас',
    'it': 'Ananas',
    'pt': 'Ananás',
  }),
  _PredefinedItemSeed(2, {
    'en': 'Mango',
    'pl': 'Mango',
    'de': 'Mango',
    'nl': 'Mango',
    'es': 'Mango',
    'fr': 'Mangue',
    'uk': 'Манго',
    'it': 'Mango',
    'pt': 'Manga',
  }),

  // Vegetables
  _PredefinedItemSeed(3, {
    'en': 'Tomato',
    'pl': 'Pomidor',
    'de': 'Tomate',
    'nl': 'Tomaat',
    'es': 'Tomate',
    'fr': 'Tomate',
    'uk': 'Помідор',
    'it': 'Pomodoro',
    'pt': 'Tomate',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Cucumber',
    'pl': 'Ogórek',
    'de': 'Gurke',
    'nl': 'Komkommer',
    'es': 'Pepino',
    'fr': 'Concombre',
    'uk': 'Огірок',
    'it': 'Cetriolo',
    'pt': 'Pepino',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Bell pepper',
    'pl': 'Papryka',
    'de': 'Paprika',
    'nl': 'Paprika',
    'es': 'Pimiento',
    'fr': 'Poivron',
    'uk': 'Перець',
    'it': 'Peperone',
    'pt': 'Pimento',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Onion',
    'pl': 'Cebula',
    'de': 'Zwiebel',
    'nl': 'Ui',
    'es': 'Cebolla',
    'fr': 'Oignon',
    'uk': 'Цибуля',
    'it': 'Cipolla',
    'pt': 'Cebola',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Garlic',
    'pl': 'Czosnek',
    'de': 'Knoblauch',
    'nl': 'Knoflook',
    'es': 'Ajo',
    'fr': 'Ail',
    'uk': 'Часник',
    'it': 'Aglio',
    'pt': 'Alho',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Carrot',
    'pl': 'Marchew',
    'de': 'Karotte',
    'nl': 'Wortel',
    'es': 'Zanahoria',
    'fr': 'Carotte',
    'uk': 'Морква',
    'it': 'Carota',
    'pt': 'Cenoura',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Lettuce',
    'pl': 'Sałata',
    'de': 'Salat',
    'nl': 'Sla',
    'es': 'Lechuga',
    'fr': 'Laitue',
    'uk': 'Салат',
    'it': 'Lattuga',
    'pt': 'Alface',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Spinach',
    'pl': 'Szpinak',
    'de': 'Spinat',
    'nl': 'Spinazie',
    'es': 'Espinaca',
    'fr': 'Épinards',
    'uk': 'Шпинат',
    'it': 'Spinaci',
    'pt': 'Espinafre',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Cabbage',
    'pl': 'Kapusta',
    'de': 'Kohl',
    'nl': 'Kool',
    'es': 'Col',
    'fr': 'Chou',
    'uk': 'Капуста',
    'it': 'Cavolo',
    'pt': 'Couve',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Cauliflower',
    'pl': 'Kalafior',
    'de': 'Blumenkohl',
    'nl': 'Bloemkool',
    'es': 'Coliflor',
    'fr': 'Chou-fleur',
    'uk': 'Цвітна капуста',
    'it': 'Cavolfiore',
    'pt': 'Couve-flor',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Broccoli',
    'pl': 'Brokuł',
    'de': 'Brokkoli',
    'nl': 'Broccoli',
    'es': 'Brócoli',
    'fr': 'Brocoli',
    'uk': 'Броколі',
    'it': 'Broccoli',
    'pt': 'Brócolos',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Zucchini',
    'pl': 'Cukinia',
    'de': 'Zucchini',
    'nl': 'Courgette',
    'es': 'Calabacín',
    'fr': 'Courgette',
    'uk': 'Кабачок',
    'it': 'Zucchina',
    'pt': 'Curgete',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Pumpkin',
    'pl': 'Dynia',
    'de': 'Kürbis',
    'nl': 'Pompoen',
    'es': 'Calabaza',
    'fr': 'Citrouille',
    'uk': 'Гарбуз',
    'it': 'Zucca',
    'pt': 'Abóbora',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Potato',
    'pl': 'Ziemniaki',
    'de': 'Kartoffeln',
    'nl': 'Aardappelen',
    'es': 'Patatas',
    'fr': 'Pommes de terre',
    'uk': 'Картопля',
    'it': 'Patate',
    'pt': 'Batatas',
  }),
  _PredefinedItemSeed(3, {
    'en': 'Beetroot',
    'pl': 'Burak',
    'de': 'Rote Bete',
    'nl': 'Biet',
    'es': 'Remolacha',
    'fr': 'Betterave',
    'uk': 'Буряк',
    'it': 'Barbabietola',
    'pt': 'Beterraba',
  }),

  // Alcohol
  _PredefinedItemSeed(4, {
    'en': 'Lager beer',
    'pl': 'Piwo jasne',
    'de': 'Helles Bier',
    'nl': 'Lagerbier',
    'es': 'Cerveza rubia',
    'fr': 'Bière blonde',
    'uk': 'Світле пиво',
    'it': 'Birra chiara',
    'pt': 'Cerveja lager',
  }),
  _PredefinedItemSeed(4, {
    'en': 'Wheat beer',
    'pl': 'Piwo pszeniczne',
    'de': 'Weizenbier',
    'nl': 'Tarwebier',
    'es': 'Cerveza de trigo',
    'fr': 'Bière de blé',
    'uk': 'Пшеничне пиво',
    'it': 'Birra di frumento',
    'pt': 'Cerveja de trigo',
  }),
  _PredefinedItemSeed(4, {
    'en': 'Non-alcoholic beer',
    'pl': 'Piwo bezalkoholowe',
    'de': 'Alkoholfreies Bier',
    'nl': 'Alcoholvrij bier',
    'es': 'Cerveza sin alcohol',
    'fr': 'Bière sans alcool',
    'uk': 'Безалкогольне пиво',
    'it': 'Birra analcolica',
    'pt': 'Cerveja sem álcool',
  }),
  _PredefinedItemSeed(4, {
    'en': 'Cider',
    'pl': 'Cydr',
    'de': 'Cider',
    'nl': 'Cider',
    'es': 'Sidra',
    'fr': 'Cidre',
    'uk': 'Сидр',
    'it': 'Sidro',
    'pt': 'Sidra',
  }),
  _PredefinedItemSeed(4, {
    'en': 'Red wine',
    'pl': 'Wino czerwone',
    'de': 'Rotwein',
    'nl': 'Rode wijn',
    'es': 'Vino tinto',
    'fr': 'Vin rouge',
    'uk': 'Червоне вино',
    'it': 'Vino rosso',
    'pt': 'Vinho tinto',
  }),
  _PredefinedItemSeed(4, {
    'en': 'White wine',
    'pl': 'Wino białe',
    'de': 'Weißwein',
    'nl': 'Witte wijn',
    'es': 'Vino blanco',
    'fr': 'Vin blanc',
    'uk': 'Біле вино',
    'it': 'Vino bianco',
    'pt': 'Vinho branco',
  }),
  _PredefinedItemSeed(4, {
    'en': 'Vodka',
    'pl': 'Wódka',
    'de': 'Wodka',
    'nl': 'Wodka',
    'es': 'Vodka',
    'fr': 'Vodka',
    'uk': 'Горілка',
    'it': 'Vodka',
    'pt': 'Vodka',
  }),
  _PredefinedItemSeed(4, {
    'en': 'Whisky',
    'pl': 'Whisky',
    'de': 'Whisky',
    'nl': 'Whisky',
    'es': 'Whisky',
    'fr': 'Whisky',
    'uk': 'Віскі',
    'it': 'Whisky',
    'pt': 'Whisky',
  }),

  // Dairy
  _PredefinedItemSeed(5, {
    'en': 'Milk',
    'pl': 'Mleko',
    'de': 'Milch',
    'nl': 'Melk',
    'es': 'Leche',
    'fr': 'Lait',
    'uk': 'Молоко',
    'it': 'Latte',
    'pt': 'Leite',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Cream',
    'pl': 'Śmietana',
    'de': 'Sahne',
    'nl': 'Room',
    'es': 'Nata',
    'fr': 'Crème',
    'uk': 'Сметана',
    'it': 'Panna',
    'pt': 'Natas',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Natural yogurt',
    'pl': 'Jogurt naturalny',
    'de': 'Naturjoghurt',
    'nl': 'Naturel yoghurt',
    'es': 'Yogur natural',
    'fr': 'Yaourt nature',
    'uk': 'Натуральний йогурт',
    'it': 'Yogurt naturale',
    'pt': 'Iogurte natural',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Greek yogurt',
    'pl': 'Jogurt grecki',
    'de': 'Griechischer Joghurt',
    'nl': 'Griekse yoghurt',
    'es': 'Yogur griego',
    'fr': 'Yaourt grec',
    'uk': 'Грецький йогурт',
    'it': 'Yogurt greco',
    'pt': 'Iogurte grego',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Fruit yogurt',
    'pl': 'Jogurt owocowy',
    'de': 'Fruchtjoghurt',
    'nl': 'Vruchtenyoghurt',
    'es': 'Yogur de frutas',
    'fr': 'Yaourt aux fruits',
    'uk': 'Фруктовий йогурт',
    'it': 'Yogurt alla frutta',
    'pt': 'Iogurte de fruta',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Kefir',
    'pl': 'Kefir',
    'de': 'Kefir',
    'nl': 'Kefir',
    'es': 'Kéfir',
    'fr': 'Kéfir',
    'uk': 'Кефір',
    'it': 'Kefir',
    'pt': 'Kefir',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Buttermilk',
    'pl': 'Maślanka',
    'de': 'Buttermilch',
    'nl': 'Karnemelk',
    'es': 'Suero de leche',
    'fr': 'Lait ribot',
    'uk': 'Маслянка',
    'it': 'Latticello',
    'pt': 'Leitelho',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Butter',
    'pl': 'Masło',
    'de': 'Butter',
    'nl': 'Boter',
    'es': 'Mantequilla',
    'fr': 'Beurre',
    'uk': 'Вершкове масло',
    'it': 'Burro',
    'pt': 'Manteiga',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Yellow cheese',
    'pl': 'Ser żółty',
    'de': 'Schnittkäse',
    'nl': 'Gele kaas',
    'es': 'Queso semicurado',
    'fr': 'Fromage à pâte dure',
    'uk': 'Твердий сир',
    'it': 'Formaggio stagionato',
    'pt': 'Queijo curado',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Cottage cheese',
    'pl': 'Twaróg',
    'de': 'Hüttenkäse',
    'nl': 'Hüttenkäse',
    'es': 'Requesón',
    'fr': 'Fromage cottage',
    'uk': 'Сир кисломолочний',
    'it': 'Fiocchi di latte',
    'pt': 'Queijo cottage',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Mozzarella',
    'pl': 'Mozzarella',
    'de': 'Mozzarella',
    'nl': 'Mozzarella',
    'es': 'Mozzarella',
    'fr': 'Mozzarella',
    'uk': 'Моцарела',
    'it': 'Mozzarella',
    'pt': 'Mozzarella',
  }),
  _PredefinedItemSeed(5, {
    'en': 'Eggs',
    'pl': 'Jajka',
    'de': 'Eier',
    'nl': 'Eieren',
    'es': 'Huevos',
    'fr': 'Œufs',
    'uk': 'Яйця',
    'it': 'Uova',
    'pt': 'Ovos',
  }),

  // Bakery
  _PredefinedItemSeed(6, {
    'en': 'White bread',
    'pl': 'Chleb pszenny',
    'de': 'Weißbrot',
    'nl': 'Wit brood',
    'es': 'Pan blanco',
    'fr': 'Pain blanc',
    'uk': 'Білий хліб',
    'it': 'Pane bianco',
    'pt': 'Pão branco',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Rye bread',
    'pl': 'Chleb żytni',
    'de': 'Roggenbrot',
    'nl': 'Roggebrood',
    'es': 'Pan de centeno',
    'fr': 'Pain de seigle',
    'uk': 'Житній хліб',
    'it': 'Pane di segale',
    'pt': 'Pão de centeio',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Wholegrain bread',
    'pl': 'Chleb pełnoziarnisty',
    'de': 'Vollkornbrot',
    'nl': 'Volkorenbrood',
    'es': 'Pan integral',
    'fr': 'Pain complet',
    'uk': 'Цільнозерновий хліб',
    'it': 'Pane integrale',
    'pt': 'Pão integral',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Toast bread',
    'pl': 'Chleb tostowy',
    'de': 'Toastbrot',
    'nl': 'Toastbrood',
    'es': 'Pan de molde',
    'fr': 'Pain de mie',
    'uk': 'Тостовий хліб',
    'it': 'Pane per toast',
    'pt': 'Pão de forma',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Kaiser roll',
    'pl': 'Bułka kajzerka',
    'de': 'Kaiserbrötchen',
    'nl': 'Kaiserbroodje',
    'es': 'Panecillo Kaiser',
    'fr': 'Petit pain Kaiser',
    'uk': 'Булочка кайзерка',
    'it': 'Panino Kaiser',
    'pt': 'Pão Kaiser',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Baguette',
    'pl': 'Bagietka',
    'de': 'Baguette',
    'nl': 'Baguette',
    'es': 'Baguette',
    'fr': 'Baguette',
    'uk': 'Багет',
    'it': 'Baguette',
    'pt': 'Baguete',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Tortilla',
    'pl': 'Tortilla',
    'de': 'Tortilla',
    'nl': 'Tortilla',
    'es': 'Tortilla',
    'fr': 'Tortilla',
    'uk': 'Тортилья',
    'it': 'Tortilla',
    'pt': 'Tortilha',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Croissant',
    'pl': 'Croissant',
    'de': 'Croissant',
    'nl': 'Croissant',
    'es': 'Cruasán',
    'fr': 'Croissant',
    'uk': 'Круасан',
    'it': 'Croissant',
    'pt': 'Croissant',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Donut',
    'pl': 'Pączek',
    'de': 'Berliner',
    'nl': 'Donut',
    'es': 'Dónut',
    'fr': 'Beignet',
    'uk': 'Пончик',
    'it': 'Ciambella',
    'pt': 'Donut',
  }),
  _PredefinedItemSeed(6, {
    'en': 'Breadcrumbs',
    'pl': 'Bułka tarta',
    'de': 'Paniermehl',
    'nl': 'Paneermeel',
    'es': 'Pan rallado',
    'fr': 'Chapelure',
    'uk': 'Панірувальні сухарі',
    'it': 'Pangrattato',
    'pt': 'Pão ralado',
  }),

  // Meat
  _PredefinedItemSeed(7, {
    'en': 'Chicken breast',
    'pl': 'Pierś z kurczaka',
    'de': 'Hähnchenbrust',
    'nl': 'Kipfilet',
    'es': 'Pechuga de pollo',
    'fr': 'Blanc de poulet',
    'uk': 'Куряча грудка',
    'it': 'Petto di pollo',
    'pt': 'Peito de frango',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Chicken thighs',
    'pl': 'Udka z kurczaka',
    'de': 'Hähnchenschenkel',
    'nl': 'Kippenbouten',
    'es': 'Muslos de pollo',
    'fr': 'Cuisses de poulet',
    'uk': 'Курячі стегенця',
    'it': 'Cosce di pollo',
    'pt': 'Coxas de frango',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Turkey fillet',
    'pl': 'Filet z indyka',
    'de': 'Putenfilet',
    'nl': 'Kalkoenfilet',
    'es': 'Filete de pavo',
    'fr': 'Filet de dinde',
    'uk': 'Філе індички',
    'it': 'Filetto di tacchino',
    'pt': 'Filé de peru',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Ground beef',
    'pl': 'Mięso mielone wołowe',
    'de': 'Rinderhackfleisch',
    'nl': 'Rundergehakt',
    'es': 'Carne picada de ternera',
    'fr': 'Bœuf haché',
    'uk': 'Яловичий фарш',
    'it': 'Carne macinata di manzo',
    'pt': 'Carne picada de vaca',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Ground pork',
    'pl': 'Mięso mielone wieprzowe',
    'de': 'Schweinehackfleisch',
    'nl': 'Varkensgehakt',
    'es': 'Carne picada de cerdo',
    'fr': 'Porc haché',
    'uk': 'Свинячий фарш',
    'it': 'Carne macinata di maiale',
    'pt': 'Carne picada de porco',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Pork loin',
    'pl': 'Schab',
    'de': 'Schweinelende',
    'nl': 'Varkenslende',
    'es': 'Lomo de cerdo',
    'fr': 'Longe de porc',
    'uk': 'Свиняча корейка',
    'it': 'Lombo di maiale',
    'pt': 'Lombo de porco',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Bacon',
    'pl': 'Boczek',
    'de': 'Speck',
    'nl': 'Spek',
    'es': 'Beicon',
    'fr': 'Lard',
    'uk': 'Бекон',
    'it': 'Pancetta',
    'pt': 'Bacon',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Ham',
    'pl': 'Szynka',
    'de': 'Schinken',
    'nl': 'Ham',
    'es': 'Jamón',
    'fr': 'Jambon',
    'uk': 'Шинка',
    'it': 'Prosciutto',
    'pt': 'Fiambre',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Sausage',
    'pl': 'Kiełbasa',
    'de': 'Wurst',
    'nl': 'Worst',
    'es': 'Salchicha',
    'fr': 'Saucisse',
    'uk': 'Ковбаса',
    'it': 'Salsiccia',
    'pt': 'Salsicha',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Salami',
    'pl': 'Salami',
    'de': 'Salami',
    'nl': 'Salami',
    'es': 'Salami',
    'fr': 'Salami',
    'uk': 'Салямі',
    'it': 'Salame',
    'pt': 'Salame',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Salmon',
    'pl': 'Łosoś',
    'de': 'Lachs',
    'nl': 'Zalm',
    'es': 'Salmón',
    'fr': 'Saumon',
    'uk': 'Лосось',
    'it': 'Salmone',
    'pt': 'Salmão',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Cod',
    'pl': 'Dorsz',
    'de': 'Kabeljau',
    'nl': 'Kabeljauw',
    'es': 'Bacalao',
    'fr': 'Cabillaud',
    'uk': 'Тріска',
    'it': 'Merluzzo',
    'pt': 'Bacalhau fresco',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Tuna',
    'pl': 'Tuńczyk',
    'de': 'Thunfisch',
    'nl': 'Tonijn',
    'es': 'Atún',
    'fr': 'Thon',
    'uk': 'Тунець',
    'it': 'Tonno',
    'pt': 'Atum',
  }),
  _PredefinedItemSeed(7, {
    'en': 'Shrimp',
    'pl': 'Krewetki',
    'de': 'Garnelen',
    'nl': 'Garnalen',
    'es': 'Gambas',
    'fr': 'Crevettes',
    'uk': 'Креветки',
    'it': 'Gamberi',
    'pt': 'Camarão',
  }),

  // Frozen
  _PredefinedItemSeed(8, {
    'en': 'Frozen pizza',
    'pl': 'Pizza mrożona',
    'de': 'Tiefkühlpizza',
    'nl': 'Diepvriespizza',
    'es': 'Pizza congelada',
    'fr': 'Pizza surgelée',
    'uk': 'Заморожена піца',
    'it': 'Pizza surgelata',
    'pt': 'Pizza congelada',
  }),
  _PredefinedItemSeed(8, {
    'en': 'Frozen fries',
    'pl': 'Frytki mrożone',
    'de': 'Tiefkühlpommes',
    'nl': 'Diepvriesfriet',
    'es': 'Patatas fritas congeladas',
    'fr': 'Frites surgelées',
    'uk': 'Заморожена картопля фрі',
    'it': 'Patatine surgelate',
    'pt': 'Batatas fritas congeladas',
  }),
  _PredefinedItemSeed(8, {
    'en': 'Frozen vegetables',
    'pl': 'Warzywa mrożone',
    'de': 'Tiefkühlgemüse',
    'nl': 'Diepvriesgroenten',
    'es': 'Verduras congeladas',
    'fr': 'Légumes surgelés',
    'uk': 'Заморожені овочі',
    'it': 'Verdure surgelate',
    'pt': 'Legumes congelados',
  }),
  _PredefinedItemSeed(8, {
    'en': 'Frozen fruit',
    'pl': 'Owoce mrożone',
    'de': 'Tiefkühlobst',
    'nl': 'Diepvriesfruit',
    'es': 'Fruta congelada',
    'fr': 'Fruits surgelés',
    'uk': 'Заморожені фрукти',
    'it': 'Frutta surgelata',
    'pt': 'Fruta congelada',
  }),
  _PredefinedItemSeed(8, {
    'en': 'Frozen dumplings',
    'pl': 'Pierogi mrożone',
    'de': 'Tiefkühlte Teigtaschen',
    'nl': 'Diepvriesdumplings',
    'es': 'Empanadillas congeladas',
    'fr': 'Raviolis surgelés',
    'uk': 'Заморожені вареники',
    'it': 'Ravioli surgelati',
    'pt': 'Rissóis congelados',
  }),
  _PredefinedItemSeed(8, {
    'en': 'Frozen fish',
    'pl': 'Ryba mrożona',
    'de': 'Tiefkühlfisch',
    'nl': 'Diepvriesvis',
    'es': 'Pescado congelado',
    'fr': 'Poisson surgelé',
    'uk': 'Заморожена риба',
    'it': 'Pesce surgelato',
    'pt': 'Peixe congelado',
  }),
  _PredefinedItemSeed(8, {
    'en': 'Vanilla ice cream',
    'pl': 'Lody waniliowe',
    'de': 'Vanilleeis',
    'nl': 'Vanille-ijs',
    'es': 'Helado de vainilla',
    'fr': 'Glace à la vanille',
    'uk': 'Ванільне морозиво',
    'it': 'Gelato alla vaniglia',
    'pt': 'Gelado de baunilha',
  }),
  _PredefinedItemSeed(8, {
    'en': 'Ice cubes',
    'pl': 'Kostki lodu',
    'de': 'Eiswürfel',
    'nl': 'IJsblokjes',
    'es': 'Cubitos de hielo',
    'fr': 'Glaçons',
    'uk': 'Кубики льоду',
    'it': 'Cubetti di ghiaccio',
    'pt': 'Cubos de gelo',
  }),

  // Household
  _PredefinedItemSeed(9, {
    'en': 'Dish soap',
    'pl': 'Płyn do naczyń',
    'de': 'Spülmittel',
    'nl': 'Afwasmiddel',
    'es': 'Lavavajillas',
    'fr': 'Liquide vaisselle',
    'uk': 'Засіб для миття посуду',
    'it': 'Detersivo per piatti',
    'pt': 'Detergente da loiça',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Dishwasher tablets',
    'pl': 'Tabletki do zmywarki',
    'de': 'Spülmaschinentabs',
    'nl': 'Vaatwastabletten',
    'es': 'Pastillas para lavavajillas',
    'fr': 'Pastilles pour lave-vaisselle',
    'uk': 'Таблетки для посудомийної машини',
    'it': 'Pastiglie per lavastoviglie',
    'pt': 'Pastilhas para máquina da loiça',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Laundry powder',
    'pl': 'Proszek do prania',
    'de': 'Waschpulver',
    'nl': 'Waspoeder',
    'es': 'Detergente en polvo',
    'fr': 'Lessive en poudre',
    'uk': 'Пральний порошок',
    'it': 'Detersivo in polvere',
    'pt': 'Detergente em pó',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Fabric softener',
    'pl': 'Płyn do płukania',
    'de': 'Weichspüler',
    'nl': 'Wasverzachter',
    'es': 'Suavizante',
    'fr': 'Assouplissant',
    'uk': 'Ополіскувач для білизни',
    'it': 'Ammorbidente',
    'pt': 'Amaciador',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Bar soap',
    'pl': 'Mydło w kostce',
    'de': 'Stückseife',
    'nl': 'Zeepblok',
    'es': 'Jabón en pastilla',
    'fr': 'Savon solide',
    'uk': 'Тверде мило',
    'it': 'Sapone solido',
    'pt': 'Sabão em barra',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Liquid soap',
    'pl': 'Mydło w płynie',
    'de': 'Flüssigseife',
    'nl': 'Vloeibare zeep',
    'es': 'Jabón líquido',
    'fr': 'Savon liquide',
    'uk': 'Рідке мило',
    'it': 'Sapone liquido',
    'pt': 'Sabonete líquido',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Shampoo',
    'pl': 'Szampon',
    'de': 'Shampoo',
    'nl': 'Shampoo',
    'es': 'Champú',
    'fr': 'Shampooing',
    'uk': 'Шампунь',
    'it': 'Shampoo',
    'pt': 'Champô',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Toothpaste',
    'pl': 'Pasta do zębów',
    'de': 'Zahnpasta',
    'nl': 'Tandpasta',
    'es': 'Pasta de dientes',
    'fr': 'Dentifrice',
    'uk': 'Зубна паста',
    'it': 'Dentifricio',
    'pt': 'Pasta de dentes',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Toothbrush',
    'pl': 'Szczoteczka do zębów',
    'de': 'Zahnbürste',
    'nl': 'Tandenborstel',
    'es': 'Cepillo de dientes',
    'fr': 'Brosse à dents',
    'uk': 'Зубна щітка',
    'it': 'Spazzolino da denti',
    'pt': 'Escova de dentes',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Toilet paper',
    'pl': 'Papier toaletowy',
    'de': 'Toilettenpapier',
    'nl': 'Toiletpapier',
    'es': 'Papel higiénico',
    'fr': 'Papier toilette',
    'uk': 'Туалетний папір',
    'it': 'Carta igienica',
    'pt': 'Papel higiénico',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Paper towels',
    'pl': 'Ręcznik papierowy',
    'de': 'Küchenpapier',
    'nl': 'Keukenpapier',
    'es': 'Papel de cocina',
    'fr': 'Essuie-tout',
    'uk': 'Паперові рушники',
    'it': 'Carta da cucina',
    'pt': 'Rolo de cozinha',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Tissues',
    'pl': 'Chusteczki higieniczne',
    'de': 'Taschentücher',
    'nl': 'Zakdoekjes',
    'es': 'Pañuelos de papel',
    'fr': 'Mouchoirs',
    'uk': 'Паперові хустинки',
    'it': 'Fazzoletti',
    'pt': 'Lenços de papel',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Trash bags',
    'pl': 'Worki na śmieci',
    'de': 'Müllbeutel',
    'nl': 'Vuilniszakken',
    'es': 'Bolsas de basura',
    'fr': 'Sacs poubelle',
    'uk': 'Пакети для сміття',
    'it': 'Sacchetti della spazzatura',
    'pt': 'Sacos do lixo',
  }),
  _PredefinedItemSeed(9, {
    'en': 'Deodorant',
    'pl': 'Dezodorant',
    'de': 'Deodorant',
    'nl': 'Deodorant',
    'es': 'Desodorante',
    'fr': 'Déodorant',
    'uk': 'Дезодорант',
    'it': 'Deodorante',
    'pt': 'Desodorizante',
  }),
];
